name: 'vanagon_snyk_scan_action'
description: 'Scans vanagon builds for ruby dependencies and untrusted repos'
inputs:
  snyk_token:
    description: 'snyk access token'
    required: true
  snyk_org:
    description: 'snyk org to write results to'
    required: true
outputs:
  vulns: # id of output
    description: 'Array of vulnerable packages'
  licenses: # id of output
    description: 'Array of license issues'
  warning_repos:
    description: 'Array of non-puppet non-trusted repos in use'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}