name: 'vanagon_snyk_scan_action'
description: 'Scans vanagon builds for ruby dependencies and untrusted repos'
# inputs:
#   targets:  # id of input
#     description: 'comma separated list in the form <project>_<platform> that should be tested '
#     required: true
#     default: ''
outputs:
  vulns: # id of output
    description: 'Array of vulnerable packages'
  licenses: # id of output
    description: 'Array of license issues'
  warning_repos:
    description: 'Array of non-puppet non-trusted repos in use'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}