name: 'vanagon_snyk_scan_action'
description: 'Scans vanagon builds for ruby dependencies and untrusted repos'
inputs:
  snykToken:
    description: 'snyk access token'
    required: true
  snykOrg:
    description: 'snyk org to write results to'
    required: true
  noMonitor:
    description: 'allows skipping the snyk monitor step'
    required: false
  skipProjects:
    description: 'A comma separated list of projects to skip'
    required: false
  skipPlatforms:
    description: 'A comma separated list of platforms to skip'
    required: false
outputs:
  vulns: # id of output
    description: 'Array of vulnerable packages'
  # licenses: # id of output
  #   description: 'Array of license issues'
  warning_repos:
    description: 'Array of non-puppet non-trusted repos in use'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}